# Generated by Django 4.1.7 on 2023-04-07 17:31

from django.db import migrations
from django.conf import settings
import os

project_root = os.path.dirname(settings.BASE_DIR)
inserta_tablas_path = os.path.join(project_root, 'sql', 'inserta_tablas.sql')

with open(inserta_tablas_path, 'r') as f:
    inserta_tablas = f.read()


class Migration(migrations.Migration):

    initial = True

    dependencies = [('app', '0001_initial'),
                    ]

    operations = [
        migrations.RunSQL(inserta_tablas),
    ]
