# Generated by Django 4.1.7 on 2023-04-07 17:31

from django.db import migrations

with open('..\sql\inserta_tablas.sql', 'r') as f:
    inserta_tablas = f.read()

class Migration(migrations.Migration):

    initial = True

    dependencies = [('app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(inserta_tablas),
    ]
