# Generated by Django 4.1.7 on 2023-04-15 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_create_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='impuesto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
        migrations.AddField(
            model_name='venta',
            name='fechaHora',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(),
        ),
    ]
