# Generated by Django 4.1.7 on 2023-04-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_detalleventa_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fechaHora',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
