# Generated by Django 4.1.7 on 2023-04-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_venta_fechahora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='fechaHora',
            new_name='fecha',
        ),
    ]
