
INSERT INTO app_categoria(NOMBRE) VALUES('AVENTURA');
INSERT INTO app_categoria(NOMBRE) VALUES('GUERRA');
INSERT INTO app_categoria(NOMBRE) VALUES('PLATAFORMA');
INSERT INTO app_categoria(NOMBRE) VALUES('TERROR');
INSERT INTO app_categoria(NOMBRE) VALUES('RPG');

INSERT INTO app_metodopago(NOMBRE) VALUES('DEBITO');
INSERT INTO app_metodopago(NOMBRE) VALUES('CREDTIO');
INSERT INTO app_metodopago(NOMBRE) VALUES('TRANSFERENCIA');


COMMIT;