
INSERT INTO app_categoria(NOMBRE) VALUES('AVENTURA');
INSERT INTO app_categoria(NOMBRE) VALUES('GUERRA');
INSERT INTO app_categoria(NOMBRE) VALUES('PLATAFORMA');
INSERT INTO app_categoria(NOMBRE) VALUES('TERROR');
INSERT INTO app_categoria(NOMBRE) VALUES('RPG');

INSERT INTO app_metodopago(NOMBRE) VALUES('DEBITO');
INSERT INTO app_metodopago(NOMBRE) VALUES('CREDTIO');
INSERT INTO app_metodopago(NOMBRE) VALUES('TRANSFERENCIA');

INSERT INTO app_juego(NOMBRE, PRECIO_VENTA, STOCK, DESCRIPCION, DISPONIBLE, ID_CATEGORIA_ID) 
    VALUES('wor', 5900, 5, 'un juego', 'y', 4);

INSERT INTO app_usuario(NOMBRE, AP_PATERNO, AP_MATERNO, F_NACIMIENTO, CORREO, DIRECCION, USUARIO, CONTRASENIA, IS_ADMIN) 
    VALUES('daniel', 'barriga', 'molina', TO_DATE('17/04/1996','DD/MM/YYYY'), 'd.barrigamolina@gmail.com', 'nn', 'ignel462', 'Ignel462', 'y');

INSERT INTO app_venta(IMPUESTO, TOTAL, FECHA, ID_METODO_PAGO_ID, ID_USUARIO_ID) 
    VALUES (10, 59900, SYSDATE, 1, 1);

INSERT INTO app_detalleventa(ID_VENTA, ID_JUEGO, CANTIDAD, PRECIO, DESCUENTO) 
    VALUES (1, 1, 10, 59900, 5);

COMMIT;